name: Secure CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ess-machine
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install deps
        run: npm i

  sast:
    runs-on: ess-machine
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dependency-scan:
    runs-on: ess-machine
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Audit dependencies
        run: npm audit --audit-level=high

  secret-scan:
    runs-on: ess-machine
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Scan secrets
        uses: gitleaks/gitleaks-action@v2

  trivy-scan:
    runs-on: ess-machine
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh

      - name: File system scan
        run: trivy fs --severity HIGH,CRITICAL --exit-code 1 .

  build-docker:
    runs-on: ess-machine
    needs: [trivy-scan]
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t myapp:latest .

      - name: Scan image
        run: trivy image myapp:latest

  deploy:
    runs-on: ess-machine
    needs: build-docker
    environment: production
    steps:
      - name: Deploy
        run: echo "Deploy with approval"
